version: '3.3'
services:
  stirling-pdf:
    container_name: pdf-server
    image: frooodle/s-pdf:latest
    ports:
      - '3080:8080'
    volumes:
      - /Users/boyouzho/pdf-server/trainingData:/usr/share/tessdata #Required for extra OCR languages
      - /Users/boyouzho/pdf-server/extraConfigs:/configs
      - /Users/boyouzho/pdf-server/customFiles:/customFiles/
      - /Users/boyouzho/pdf-server/logs:/logs/
    environment:
      - DOCKER_ENABLE_SECURITY=false
      - INSTALL_BOOK_AND_ADVANCED_HTML_OPS=false
      - LANGS=en_GB
